# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -lib /home/runner/work/ScriptCraft/ScriptCraft/lib
      
    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads
        
    - name: step 2 - Add artifacts to publish to the temp folder
      run: |
        cd downloads
        cp -r /home/runner/work/ScriptCraft/ScriptCraft/target/* ./
        cd ..
    
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads
